version: '3.7'

services:
  startracker-db:
    image: mysql:5.7
    container_name: ${DB_HOST}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
#    command: --init-file docker/mysql/create-database.sql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - backend

  api:
    container_name: startracker-api
    build:
      context: .
      dockerfile: api.dockerfile
      args:
        uid: ${UID}
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - ./api:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - ${API_SERVER_PORT}:80
    expose:
      - 80
    links:
      - ${DB_HOST}
    depends_on:
      - ${DB_HOST}
    networks:
      - backend

networks:
  backend:
    driver: bridge
